### ISSUE TITLE
Cannot get profiling to work

### ISSUE THREAD

**Issue by zrobinette12** [JustinAzoff/zeek-jemalloc-profiling#1]
Hello @JustinAzoff, 

I've noticed some memory issues on one of my sensors recently so I decided to compile zeek 4.0.4 with jemalloc along with this plugin to see if I could diagnose the problem.

I installed the profiling plugin via zkg and it says it successfully installs but when deploying zeek or performing a lot of zeekctl commands I get this warning.
Warning: no plugin found in /opt/zeek/lib64/zeek/plugins/packages/zeek-jemalloc-profiling/process.py

I put jeprof_enable=1 in my worker configuration but when I perform zeekctl jeprof.check it says jemalloc profiling enbaled: False.

I'm able to get other zeek packages installed like af_packet so I'm not sure what I'm doing wrong. I'm still new to this so I could very well have compiled incorrectly. I believe I got all the right dependencies though and I used this configure command to enable jemalloc without any issue.

./configure --prefix=/opt/zeek --enable-jemalloc
make
make install

If it helps, I can list out the dependancies I installed. I'm also on Centos 7 minimal install. 

Appreciate any advice you might have!

**Comment by JustinAzoff** [comment]
This one is ok:

Warning: no plugin found in /opt/zeek/lib64/zeek/plugins/packages/zeek-jemalloc-profiling/process.py

that file is not a zeekctl plugin, you can just remove it from that directory.

I just updated the pkg to prevent that from being installed there.

> when I perform zeekctl jeprof.check it says jemalloc profiling enbaled: False.

If you are getting that it is because your build of jemalloc does not have profiling enabled.  You'll need to rebuild jemalloc with `--enable-prof`

**Comment by zrobinette12** [comment]
Ah got it, I figured I had missed something during the compile. I'll try it out! Thanks!

**Comment by zrobinette12** [comment]
This worked great, thank you!
